#pragma once
/* AUTO-GENERATED by tools/gen_sprites.py — do not edit by hand.
 * Sub-image indices into the citro2d sprite sheet (gfx/sprites.t3s).
 * Only AI-generated entity sprites live in the atlas; tiles stay procedural. */

#define ATLAS_DURIO_STAND        0
#define ATLAS_DURIO_WALK0        1
#define ATLAS_DURIO_WALK1        2
#define ATLAS_DURIO_WALK2        3
#define ATLAS_DURIO_JUMP         4
#define ATLAS_DURIO_DEAD         5
#define ATLAS_CRAB_WALK0         6
#define ATLAS_CRAB_WALK1         7
#define ATLAS_SNAIL_WALK0        8
#define ATLAS_SNAIL_WALK1        9
#define ATLAS_SNAIL_SHELL        10
#define ATLAS_NUT_0              11
#define ATLAS_BG_PLANET2         12
#define ATLAS_BG_NEBULA          13
#define ATLAS_BG_MOON            14
#define ATLAS_BG_WRECK           15
#define ATLAS_BG_DEBRIS          16
#define ATLAS_BG_RIG             17

#define ATLAS_COUNT 18
