#!/usr/bin/env python3
"""
Generate NDS 4bpp tile font data from system TTF font.
Outputs C source with tile data and codepoint-to-index mapping.
"""
import sys, os, struct, re

def get_codepoints(paths):
    """Extract all unique codepoints from C string literals."""
    chars = set()
    for path in paths:
        with open(path, "rb") as f:
            raw = f.read()
        in_str = False
        buf = bytearray()
        i = 0
        while i < len(raw):
            b = raw[i]
            if b == ord('"') and (i == 0 or raw[i-1] != ord('\\')):
                if in_str:
                    for c in buf.decode("utf-8", errors="ignore"):
                        cp = ord(c)
                        if cp >= 0x20:
                            chars.add(cp)
                    buf = bytearray()
                in_str = not in_str
            elif in_str:
                if b == ord('\\') and i+1 < len(raw):
                    nb = raw[i+1]
                    if nb == ord('x') and i+3 < len(raw):
                        try:
                            buf.append(int(raw[i+2:i+4].decode("ascii"), 16))
                        except:
                            pass
                        i += 3
                    else:
                        i += 1
                else:
                    buf.append(b)
            i += 1
    for c in range(0x20, 0x7F):
        chars.add(c)
    return sorted(chars)

def render_glyphs_pillow(codepoints):
    """Render 8x8 glyphs using Pillow."""
    from PIL import Image, ImageDraw, ImageFont

    # Try to find a suitable font
    font_paths = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf",
        "/usr/share/fonts/truetype/unifont/unifont.ttf",
    ]

    font = None
    for fp in font_paths:
        if os.path.exists(fp):
            try:
                font = ImageFont.truetype(fp, 8)
                break
            except:
                continue

    if font is None:
        # Fallback: try default
        try:
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 7)
        except:
            font = ImageFont.load_default()

    glyphs = {}
    for cp in codepoints:
        img = Image.new("1", (8, 8), 0)
        draw = ImageDraw.Draw(img)
        ch = chr(cp)

        # Center the character
        try:
            bbox = draw.textbbox((0, 0), ch, font=font)
            w = bbox[2] - bbox[0]
            h = bbox[3] - bbox[1]
            x = (8 - w) // 2 - bbox[0]
            y = (8 - h) // 2 - bbox[1]
        except:
            x, y = 0, 0

        draw.text((x, y), ch, fill=1, font=font)

        # Extract 8x8 bitmap
        bitmap = []
        for row in range(8):
            val = 0
            for col in range(8):
                if img.getpixel((col, row)):
                    val |= (1 << (7 - col))
            bitmap.append(val)
        glyphs[cp] = bitmap

    return glyphs

def bitmap_to_nds_tile(bitmap):
    """Convert 8x8 1bpp bitmap to NDS 4bpp tile (32 bytes).
    NDS 4bpp: each row = 4 bytes, 2 pixels per byte, low nibble first."""
    tile = bytearray(32)
    for row in range(8):
        for col in range(8):
            pixel = 1 if (bitmap[row] & (1 << (7 - col))) else 0
            byte_idx = row * 4 + col // 2
            if col % 2 == 0:
                tile[byte_idx] |= pixel  # low nibble
            else:
                tile[byte_idx] |= (pixel << 4)  # high nibble
    return tile

def generate_c(codepoints, glyphs, output_path):
    """Generate C source file with font data."""
    with open(output_path, "w") as f:
        f.write("/* Auto-generated by font_convert.py — do not edit */\n")
        f.write("#include <stdint.h>\n\n")

        # Tile data: glyph 0 = blank, then one per codepoint
        f.write(f"/* {len(codepoints)} glyphs + 1 blank = {len(codepoints)+1} tiles */\n")
        f.write(f"const unsigned int FONT_TILE_COUNT = {len(codepoints) + 1};\n\n")

        f.write("const uint8_t FONT_TILES[] __attribute__((aligned(4))) = {\n")
        # Tile 0: blank
        f.write("    /* tile 0: blank */\n    ")
        f.write(", ".join(["0x00"] * 32))
        f.write(",\n")

        for idx, cp in enumerate(codepoints):
            tile = bitmap_to_nds_tile(glyphs[cp])
            f.write(f"    /* tile {idx+1}: U+{cp:04X} '{chr(cp) if cp >= 0x20 and cp < 0x7F else '?'}' */\n    ")
            f.write(", ".join(f"0x{b:02X}" for b in tile))
            f.write(",\n")

        f.write("};\n\n")

        # Codepoint to tile index mapping
        # Generate lookup tables per Unicode block for O(1) lookup

        # ASCII: direct table 0x20-0x7E
        f.write("/* ASCII 0x20-0x7E → tile index (0 = not found) */\n")
        f.write("const uint16_t FONT_ASCII[95] = {\n    ")
        ascii_map = []
        for cp in range(0x20, 0x7F):
            if cp in codepoints:
                ascii_map.append(codepoints.index(cp) + 1)
            else:
                ascii_map.append(0)
        f.write(", ".join(str(x) for x in ascii_map))
        f.write("\n};\n\n")

        # Non-ASCII: sorted table for binary search
        non_ascii = [(cp, codepoints.index(cp) + 1) for cp in codepoints if cp >= 0x80]
        f.write(f"/* Non-ASCII: {len(non_ascii)} entries, sorted by codepoint */\n")
        f.write(f"const unsigned int FONT_EXT_COUNT = {len(non_ascii)};\n")
        f.write("typedef struct { uint16_t cp; uint16_t tile; } FontExtEntry;\n")
        f.write("const FontExtEntry FONT_EXT[] = {\n")
        for cp, tile in non_ascii:
            f.write(f"    {{ 0x{cp:04X}, {tile} }}, /* {chr(cp)} */\n")
        f.write("};\n")

    print(f"Generated {output_path}: {len(codepoints)+1} tiles, {len(non_ascii)} ext entries")

def main():
    string_files = sys.argv[1:-1]
    output = sys.argv[-1]

    codepoints = get_codepoints(string_files)
    print(f"Found {len(codepoints)} unique codepoints")

    glyphs = render_glyphs_pillow(codepoints)
    generate_c(codepoints, glyphs, output)

if __name__ == "__main__":
    main()
